services:
  app:
    image: noozecrypt/rent-video
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rent-video
      SPRING_DATASOURCE_USERNAME: rent-video
      SPRING_DATASOURCE_PASSWORD: rent-video
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rent-video
      POSTGRES_USER: rent-video
      POSTGRES_PASSWORD: rent-video
    ports:
      - "5432:5432"